name: Dataform CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  dataform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SQLFluff
        run: pip install sqlfluff sqlfluff-templater-dataform

      - name: Verify changed SQL files
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20
        id: verify-changed-sql
        with:
          files: |
            **/*.sql
            **/*.sqlx
      - name: Run SQLFluff lint (changed files only)
        if: steps.verify-changed-sql.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-sql.outputs.changed_files }}
        run: |
          echo "Changed SQL files:"
          echo "$CHANGED_FILES"
      
          sqlfluff lint $CHANGED_FILES \
            --dialect bigquery \
            --templater dataform



