name: Test WorkFlow

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "A job consists of"
  job-2:
    runs-on: ubuntu-24.04
    needs:
      - job-1
    steps:
      - run: echo "Something"
      
